# Generated by Django 4.2.7 on 2023-12-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_fecha_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img_name',
            new_name='image_name',
        ),
    ]
